### ISSUE TITLE
Bard playback failure: 'Lost Hope' by Xepel

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#116]
Dandelion: A31 Cannot hear 1 of Xepel’s songs. Others can hear it. I could hear his other songs before this one. • You hear Xepel’s music...<br />Xepel starts playing his violène.
* Failed to play song.: unexpected(got: “1”)
(Xepel): Lost Hope<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1604201082123500<br /><br />Jamboree<br /><br />Bard music is complicated....

**Comment by mehancl** [comment]
Got the notes and added this to master ticket #163
