### ISSUE TITLE
Sidebar and text log should detect URLs and make them clickable

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#126]
Shard: • The "• What's New" URL isn't an active link.<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1605331415161000<br /><br />Skirwan<br /><br />Yup, I'm not doing link detection anywhere yet. :thumbsup:

**Comment by dfsw** [comment]
should also link detect in log
