### ISSUE TITLE
New UI button for toggles clan name display in players window

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#130]
Shard: • In Players window, it would help to have a tooltip for the left-most button that toggles clan name display. Or use a word instead of icon to make it explicit what the button does.<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1605332166164800<br /><br />Skirwan<br /><br />At some point I'm going to the list of UI icons I think I need and solicit ideas. The hamburger was just the least-wrong built-in image. :slightly_smiling_face:

**Comment by spkzest** [comment]
This is obsolete, the icon is dead and there's now a 'detailed' checkbox in the menu.
