### ISSUE TITLE
Text formatting of a yell differs in Cliuenk vs DT

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#133]
Shard: This yell didn't format like in old client - should show up in multiple lines with "BEER" displayed vertically. Instead just got one line of dots.<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1605486930170700

**Comment by mehancl** [comment]
Shard: Shard yells, "......................B..........................................E.E.........................................E.E..........................................R......................"

**Comment by skirwan** [comment]
Additional test case from #124:

`<= LastListLestLastLost #1 =>` should fill the full width

**Comment by skirwan** [comment]
Pretty sure this is fixed in A39, but we should get Shard to check any other bubble-formatting-sensitive macros he has.
