### ISSUE TITLE
A37-Bard Concert music caused high CPU and loss of sound

### ISSUE THREAD

**Issue by ryanima1** [skirwan/clan-lord-client-issues#156]
During this last bard concert a new song named "Drifting" by cloud produced no sound and caused the cpu to spike over 100% for both of the currently running Clieunk processes.  For both clients, all game functions continued to work except sound.  No in game errors were visible.

![Screen Shot 2020-11-29 at 4 08 56 PM](https://user-images.githubusercontent.com/75224597/100554286-b08a4400-3261-11eb-977e-cb9d932d3a84.png)

**Comment by mehancl** [comment]
Put in master bard ticket #163 . Closing
