### ISSUE TITLE
A37- Mid Song error durring bard concert

### ISSUE THREAD

**Issue by ryanima1** [skirwan/clan-lord-client-issues#157]
During the latest bard concert, A song by Aspasia, mid song the client tried to start playing the song again, stopped the original playback, and then threw an error. The following was the only logged error:
11/29/20 4:15:16p • You hear Aspasia's music...
11/29/20 4:15:16p Aspasia starts playing her lucky lyra.
11/29/20 4:15:16p * Tried to play a song while already playing.

It did not seem to affect any others in game.

I'm not quite sure if the game erroneously tried to play her song a second time, if she did so in her song, or if something else was amiss.  However, it didn't appear to to affect anyone else and it did not seem to force excessive cpu or break in game sound like my previous bug.  The next bard song played normally without client restart.

**Comment by mehancl** [comment]
Closing - not enough info to diagnose an issue.
