### ISSUE TITLE
Bottom health bar looks like there's some left in it when there's not

### ISSUE THREAD

**Issue by mcmanuss8** [skirwan/clan-lord-client-issues#162]
![Screen Shot 2020-12-20 at 10 43 33 PM](https://user-images.githubusercontent.com/5892502/102737309-16279880-4315-11eb-93f0-cb2f38f3ce50.png)

Don't have DT client on this machine to A/B but I don't recall seeing a sliver of green when fallen before. Compare to the topleft bars:
![Screen Shot 2020-12-20 at 10 46 43 PM](https://user-images.githubusercontent.com/5892502/102737384-4707cd80-4315-11eb-92a6-b2e718681fa5.png)

**Comment by skirwan** [comment]
Pretty sure A39 fixes this -- feign death is really handy for reproducing.
