### ISSUE TITLE
MASTER TICKET: Bard Issues (Playing/Hearing)

### ISSUE THREAD

**Issue by mehancl** [skirwan/clan-lord-client-issues#163]
Master bard ticket for all bard-related issues. If the issue is related to a song playing improperly, please supply notes from the Bard. Do **not** simply say "Issue playing <name of song>" as that doesn't help!

**Comment by mehancl** [comment]
During this last bard concert a new song named "Drifting" by cloud produced no sound and caused the cpu to spike over 100% for both of the currently running Clieunk processes. For both clients, all game functions continued to work except sound. No in game errors were visible.
![100554286-b08a4400-3261-11eb-977e-cb9d932d3a84](https://user-images.githubusercontent.com/75183627/103190864-be52d980-48a0-11eb-9e5b-c1b386d35064.png)

**Comment by mehancl** [comment]
When a bard plays an invalid song, the error messages should be hidden from listeners. Apparently the song gets relayed unconditionally -- there's no server-side validation.

**Comment by mehancl** [comment]
Issue: Spammed “•You hear Xepel’s music…” 6x
12/20/20 23:06:21 * Failed to play song.: general(“Polyphony overflow (129)“)
12/20/20 23:06:21 (Xepel): “Sans Soul Lament, For Mortica”by Forey
From Xepel:
“/use /part @60((([\c=d#/g]$p8p[/g]$dg=b[\c=d#]$[\f#=a#/d#]$p8[/d#d]$p6[/d]$c[\f#=a#]$)([\c=d#/g]$p8p[/g]$dg=b[\c=d#]$[\f#=a#/d#]$p8[/d#f]$p6[/f]$c[\f#=a#]$))2[\g#=d#/a#]$p6a#[\g#g]$[/a#g]$pc1d1d#1d1c[\g=d#/g]$[\d=f/a]$p6a[\d=/a]$[\g#/b#]$=f/c=g#f/cgf#b#[\g#=f/b#]$)[\d#=g/b#]$p8[\d#=g/b#]$([\d=d]$p/DcDec[\d=d]$[\c=c]$p/C=a#/Cdc[\c=c]$)2([\d=d]$/g6fe8[\d=d]$[\c=c]$/f6ed8[\c=c]$)([\d=d]$/g6fEC[\d=d]$[\c=c]$/f6eDC[\c=c]$)[\cd#g]$p[\d#=d#]$p[\g/g]$p8p4[\c=d#/g]$[\dfa]$p[\f=f]$p[\a/a]$p\r” “/use 8p4[\d=f/a]$[\cd#g]$p[\d#=d#]$p[\g/g]$p6=g1f1d#c[\c=d#/g]$[\da#f]$p[\a#=a#]$p[\f/f]$p6=f1g1g#f[\d=a#/f]$((([\c=d#/g]$p8p[/g]$dg=b[\c=d#]$[\f#=a#/d#]$p8[/d#d]$p6[/d]$c[\f#=a#]$)([\c=d#/g]$p8p[/g]$dg=b[\c=d#]$[\f#=a#/d#]$p8[/d#f]$p6[/f]$c[\f#=a#]$))[\g#=d#/a#]$p6a#[\g#g]$[/a#g]$pc1d1d#1d1c[\g=d#/g]$[\d=f/a]$p6a[\d=/a]$[\g#/b#]$=f/c=g#f/cgf#b#[\g#=f/b#]$)[\d#=g/b#]$p8p8\r” “/narrate “Sans Soul Lament, For Mortica”by Forey\r”

**Comment by mehancl** [comment]
Skirwan: > Cloud starts playing his starbuck harp.
> * Failed to play song.: unexpected(got: "")


https://clieunk.slack.com/archives/C018PCWS9T2/p1603678751059400

Missed server frame. Got 6833734 but wanted 6833733
Ignoring reliable stream for 6833734, reliable segment isn't in sequence
Got catchup packet 6833735, replayed from 6833733
Frame 6833735, got 3 reliable frames.
BardPlayer command: SongCommand(who: Optional("11729872"), with: [], instrument: 2, forSelf: false, initialVolume: 100, initialTempo: 60, body: ClanLord.SongCommand.Body.partial(notes: "(\g\a#=d_d#gp4)2\a=c_e_f#gp4\g_a#=d_d#gp4\g_a#=d_d#g_d#d\a#g\a#=d_d#g_d#d(\a#[g/a]p2\a#[=d/g]p2=d#[g/a]p2=d#[d/g]p2)3\a#[g/a=a]p2=a#/d_d#g_d#d=a#[g\g]p2a#=d_d#g_d#d\a#[\g=g]p2a#/d_d#g_d#d=a#[g\a]p2=c_e_f#g_f#e_c[\a=a]p2/c_e_f#g_f#/e_c[=a\a]p2=c_e_f#g_f#e_c[/cef#]9\a=c_e_f#g_f#e_c[/df#a]9\a=c=e_f#g_f#e_c[/a#ge]9\a=c_e_f#g_f#e_c\g_a#=d_d#g_d#d(\a#[g/a]p2\a#[=d/g]p2=d#[g/a]p2=d#[d/g]p2)2\a#"))
Music from 11729872, group ["11729872"]: PARTIAL
Extending stream existing stream
BardPlayer command: SongCommand(who: Optional("11729872"), with: [], instrument: 2, forSelf: false, initialVolume: 100, initialTempo: 60, body: ClanLord.SongCommand.Body.notes(notes: "[\g/a=a]p2c_e_f#g_f#e_c[=a\a]p2/c_e_f#/g_f#e_c[\a=a]p2c_ef#=g_f#e_c[\a=a]p2/c_e_f#g_f#e_c[=a\g]p2a#=d_d#g_d#d\a#[\g=g]p2=a#/d_d#g_d#d=a#[g\g]p2a#=d_d#g_d#d\a#[=ga#/d]8\g2_\a#2_[=a/df#]9=d2_d#2_[/dga#]9=g9"))
Music from 11729872, group ["11729872"]: END NOTES
Updating existing stream

Coriakin

Looks like Cloud is living in the past! _ hasn't done anything for a long time. Originally it was supposed to make the notes sound more connected ("legato" playing), possibly by extending them slightly, but as far as I know it hasn't done anything for a long time. I suspect most bard music programs just ignore _ characters, and Clieunk can do the same

**Comment by mfriedlee** [comment]
Issue: Audio did not play (A36 or A38)

**EDIT: Tested A38 and appears to be related to presence of underscore characters in song. With underscores removed, appears to play normally.

From (Rakshasa): "Ma'Taline, the Sun Sets"

"/equip bagpipe\r"
"/use /part @60[d#a#]$p8/D#G#a#9\A#[=d#a#]$[c#g#]$p8/C#F#G#f#g#c#9\a#6[=c#g#]$[d#g#a#]$p8/D#F#G#A#d#5\A#[=d#g#a#]$[c#g#]$p8/c#d#D#F#=G#a#9[c#g#]$([\a#=d#a#]9p9[\a#=d#a#]3p3[c#g#/c#]3p3[\g#=c#g#]6p6)2[\f#=c#]$p8=g#f#/D#F#=g#5a#6[\f#=c#]$(([\g#=c#]2g1p1)2p[\g#=c#]2g1p1p|1([\g#=c#]1g1)2p3@170\a#1b1=c#1g#1a#3@60|2p)2\r"
"/use /part d#_a#_g#[d#a#]$(d#1f#1g#1a#1)3d#1f#1[/c#]2=a#1g#1[d#a#]$[c#a#]$(c#1f#1g#1a#1)3c#1a#1[/c#]2=g#1a#1[c#a#]$[/d#=d#a#]$(d#1f#1g#1a#1)3d#1f#1[/d#=d#a#]$[/c#=d#a#]2a#1g#1[/c#=c#a#]$(c#1f#1g#1a#1)3[/c#=c#a#]$c#[/g#\c#=a#]2=g#[/a#\d#=a#]$(d#1f#1g#1a#1)3d#1a#1[/a#\d#=a#]$\r"
"/use /part [/a#]2[\f]1=g#1[\d#]1=a#1[/a#\c#=a#]$(c#1f#1g#1a#1)3c#1a#1g#1a#1[/a#\c#=a#]$[/a#\d#=a#]$(d#1f#1g#1a#1)3d#1a#1[/a#\d#=a#]$[/a#\d#=a#]2g#1a#1[/a#\d#=a#]1d#1[/a#\c#=a#]$f#1g#1a#1c#1f#1g#1a#1[/a#\c#=a#]$[/g#\c#=g#]$c#1f#1g#1a#1[/g#\c#=g#]$\r"
"/use /part c#[/g#\c#=a#]2\a#1g#1[/a#\d#]$(=[d#]1\d#1[f#]1=f#1[g#]1\g#1[a#]1=a#1)3[d#]1\d#1[a#]1=a#1[/a#\d#]$[/a#]4[\f]1=g#1[\d#]1=a#1[\c#]1=c#1[\d#]1=f#1[/a#\c#]6[\g#]1=g#1[a#]1\a#1[=g#]1c#1[f#]1\f#1[g#]1=g#1[d#]1a#1[g#\c#]$[g#]1=c#1[=f#]1/d#1[f#]1=g#1[a#]1/g#1[a#]1=c#1[a#]1/g#1[f#]1=g#1[/d#]1a#1[=g#\c#]$[d#=a#]$([d#]1\d#1[f#]1=f#1[g#]1\g#1[a#]1=a#1)3[d#]1\d#1[a#]1=a#1[a#\d#]$[=a#\d#]2[g#]1=g#1[a#]1\a#1[\d#=a#]1c#1[/c#\f#]$=f#1g#1a#1(c#1f#1g#1a#1)2[/c#\f#]$[/c#]9=c#a#g#3%9a#9\r"
"/use @60%8[%8d#a#]$p8/D#G#a#9\A#[=d#a#]$[c#g#]$p8/C#F#G#f#g#c#\a#9%7[%7=c#g#]$[d#g#a#]$p8/D#F#g#f#g#a#d#6\A#[=d#g#a#]$[c#g#]$p8/c#d#D#F#=G#a#9[c#g#]$([\a#=d#a#]9p9[\a#=d#a#]3p3[c#g#/c#]3p3[\g#=c#g#]6p6)2%6[%6\f#=c#]$p8=g#f#/D#F#5=g#7[\f#=c#]$[%5\f#=c#a#]$(p7)3[\f#=c#a#]$\r"

**Comment by mehancl** [comment]
Crash playing the following song in A20 (https://clieunk.slack.com/archives/C018PCWS9T2/p1598572468126400):

“/use /part @180(\ggg1g1)2gg(ddd1d1)2dd(fff1f1)2ff(ccc1c1)2cd[=g]2\g[=a]2\g[=b]2\g[=g]6\ggg[=d]\gg[=g]2\d[=a]2\d[=b]2\d[=f#]6\ddd[=a]\dd[=f]2\f[=g]2\f[=a]2\f[=b]\ff[/c]\ff[/f]2\f[/e]\cc[/d]2\c[/c]6\ccc[=g]\cc(([/gb]1[=g]2\g[=a]2\g[=b]2\g[/gb]1[=g]6\ggg[/gb]1[=d]\gg[/f#a]1[=g]2\d[=a]2\d[=b]2\d[/f#a]1[=f#]6\ddd[/f#a]1[=a]\dd[/fa]1[=f]2\f[=g]2\f[=a]2\f[/fa]1[=b]\ff[/c]\f[/fa]1\f[/f]2\f[/eg]1[/e]\c[/eg]1\c[/d]2[eg]1\c[/eg]1[c]6\ccc[/gb#]2[=g]\cc)2\r”
pause 1
“/use /part |1[=b]\g[=g]\g[=f]\g[=d]\g[=f]\g[=g]\g[=b]\g[=g]\g[=b]\d[=g]\d[=f#]\d[=d]\d[=f#]\d[=a]\d[=b]\d[=a]\d[/c]\f[=a]\f[=f]\f[=d#]\f[=f]\f[=a]\f[/c]\f[/d#]\f[/e]\c[/c]\c[=b.]\c[=g]\c[=e]\c[=c]\c[=e]\c[=f#]\c([/b]6[=b]\g[=g]\g[=f]\g[/a]6[=d]\g[=f]\g[=g]\g[/g][=b]\g[=g]\g[/f#]6[=b]\d[=g]\d[=f#]\d[/g]6[=d]\d[=f#]\d[=a]\d[/a][=b]\d[=a]\d[/f]6[/c]\f[=a]\f[=f]\f[/a]6[=d#]\f[=f]\f[=a]\f[/b#][c]\f[/d#]\f[/g]6[/e]\c[/c]\c[=b.]\c[/b.]6[=g]\c[=e]\c[=c]\c[/b#][=e]\c[=f#]\c\r”
“/use /part [/b]6[=b]\g[=g]\g[=f]\g[/b]6[=d]\g[=f]\g[=g]\g[/g][=b]\g[=g]\g[/a]6[=b]\d[=g]\d[=f#]\d[/g]6[=d]\d[=f#]\d[=a]\d[/f#][=b]\d[=a]\d[/f]6[/c]\f[=a]\f[=f]\f[/f]6[=d#]\f[=f]\f[=a]\f[/a][c]\f[/d#]\f[/g]6[/e]\c[/c]\c[=b.]\c[/g]6[=g]\c[=e]\c[=c]\c[/b#c][=e]\c[=f#]\c)2([/gb]1[g]2g1a1[g]2b1=c1[g]2=d1e1[/gb]1[g]2=f#1g1[g]2=a1b1[g]2/c1d1[gb]1[g]2/e1f#1[g]2/g1b1[/f#a]1[d]2/a1g1[d]2/f#1e1[d]2/d1c#1[f#a]1[d]2=b1a1[d]2=g1f#1[d]2=e1d1[/f#a]1[d]2=c#1\b1[d]2=d1\a1\r”
pause 1
“/use /part [/fa]1[f]2f1g1[f]2a1a#1[f]2=c1d1[/fa]1[f]2=e1f1[f]2=g1a1[f]2=a#1/c1[fa]1[f]2/d1e1[f]2/f1a1[/eg]1[c]2/b#1b1[c]2/a1g1[c]2/f1e1[eg]1[c]2/d1c1[c]2=b1a1[c]2=g1f1[/eg]1[c]2=e1d1[/f#a]1[c]2=c1\g1)2)2([/gb]1[=g]\g[=d]2\g[=f#][=d]2\g[/gb]1[=g]\g[=e]\g[=a]2\g[/gb]1[=db]\gg[\a][/f#a]1[=a]2\d[=f#]2\d[=d][/d]2\d[/f#a]1[=f#]\d[=f#]\d[=e]2\d[/f#a]1[=ad]\dd[/c][/fa]1[=c]2\f[=f]2\f[=b][a]2\f[/fa]1[/c]\f[=a]\f[=b]\f[/fa]1[=f]\f[=a]2\f\r”
pause 1
“/use [=g][/eg]1[=g]\c[/eg]1\c[/c][=e]2/[eg]1\c[/eg]1[=g]6\c[/e]\cc[/gb#]2[/gc]\cc)2([/gb]1[=g/d]\g[=d]2\g[=f#/e][=d]2\g[/gb]1[=g]\g[=e/f#]\g[=a]2\g[/g][b]1[=db]\gg@-15[\a/f#][a]1[=a]2\d[=f#]2\d[/g=d][/d]2\d[/f#a]1[=f#]2\d[/a=f#]\d[=e]2\d[/f#a]1[/b=ad]\dd@-15[/b#/c][/fa]1[=c]2\f[=f]2\f[/b=b][a]2\f[/fa]1[/c]\f[/b#=a]\f[=b]\f[/fa]1[/b=f]\f[=a]2\f@-15[/b#=g][/eg]1[=g]\c[/eg]1\c[/bc][=e]2/[eg]1\c[/eg]1[=g]6\c[/ge]\cc[/g]2[/gcb#]\cc@-15)2@60[\g=dg/dgb]8=a8\r”

**Comment by mehancl** [comment]
"Spring" by Coriakin played about 60 seconds late for Clieunk listeners: 

spring
{
"/equip instrumentcase\r"
"/useitem left /remove vibra\r"
"/equip vibra\r"
pause 1
"/use /part @90%8[%1]((/d1=d1!a1|3)3/c#1@180(=da/c#)2=dbdgbdgbd|2adeade[%9/c#=c#]}ad@90[d/d]9%8!adgadg[/e=e]ad@90[f#/f#]9{|4}ade}ade[\c#/c#=c#]}ad@90[d\d/d]9%9((/d1=d1!a1|3)3{|1{)3@180/d=da/d[%7d]=da[/e]d=d(%5([/f#]6d=da[/g]6d=da[/d]8=ad[/e]6c#=da[/a]6c#=da[/e]c#=d[/e]=bd[/f#]2=g[/e]=bd[/d]2=g@90[/d]8=b1d1(a1d1g1)2@180|1[/d]=ad[/d]2=b[/c#]1=dg[/d]6=bdg[=gb]bd[/d]2=a[/c#]1=df#[/d]6=adf#[/c#e]2=a@90[/c#e]9=d1=(a1d1e1|2a1e1)3a1@180[/d]=de[/e]=ae)2[=a]/e1f#1[=d]2/g1a1[/gb]6d=dg[/f#a]6d\r"
"/use /part =dg[/g]=bd[/f#a]6=f#d[/c#]2=f#[b/d]6\b=df#[/e]2\b[/f#]2=f#@90[\g=b/d]G[\a/c#]F#[D=f#a\b]pc#[=c#ea/D]p\c#|1@90[%7\d][=d/d]8%8(/d1(=d1a1/d1[\d]1)2=d1@180([\d]8=|1/c#=da/c#|2da/c#=d|3bdgb|4dgbd)4![\d]8=adgadg[%9\c#/c#=c#]ad@90[\d=d/d]8[{{]{|2[\d]8}=ade}ade[%7\c#=c#]}A%9[%7]@90[\f#=df#]8BF#([\f#=c#f#]8aF#f#[\dGb=]8gf#d3\b1[c#g#b]8=F#[\F]p=c#|1([\f#a=d]8aB/c#|1[\ea=c#]8/dc#=A3e1)2@180[\c#f#B=e]8B6/c#1=b1[\c#f#a#=e]8A#8@90[\f#=df#]8b3a1f#1e1f#)2[\f#a=d]8ab1/c#1f#e[\ea=c#]8/dc\r"
"/use /part #=A3b1([\dga]8=ad%4/adp6=|1%7p[%5])2%9b[%7]([\df#b]8=ad%4/ad%7|1p6=b[%5])2[%7]pf#@180e1f#1edc#[\dga]8(=%7ad%4/(ad|4{)6}[%6=a]2/a[=b]2/d|1[%6\dga]8|2[%5])2%7([\dea=e]8ad%4/adad=|1a%7b[%7])2%6/ef#[{\g/dG]8%4gdgd[\a/c#F#]8f#df#d[}\b=f#a/D]8d=a[}\c#]/d=a[}c#ea/D]8d=a[\c#]/d=a@90[\d][%7=d/d]8%8|4[%5\d]4=({ade)2[%7/d]2=a[/e]=d)4|2%8[/d%7]8([=b]8[\b]/d1(=d1b1/d1|1[{\b])2=d1@180([\b]8|1/c#=da/c#|2=da/c#=d|3/e=db/e|4=db/e=d)4[\b]8/d=d|1b[}}e]2/d=[f#]2d[g]2b{[%8\b=f#]2b[bc#/]2c#@\r"
"/use /part 90{[{d=d{{]1)2[/e]=b/d[f#]=db[/c#]=bd%7@90[/d]8([%7=b]8[%8\b]2(/d1=d1|1[\a]1=b1[\b]3|2b1[\d]2)3@180[%8\a](/c#=d|1[\g]2=a[\a]6|2a[\c#])3([\g]/e=d[\f#]2=b)2[\g]2/e[\a]2=d|1/d[\f#]8=db[%7e]2/d=[f#]2d[g]2b{[%9\b=f#]2b[bc#/]2c#%6@90[d]1)2[\b]9/d[%\f#=d]}}/c#1d1{{[e=e]b/d[f#=f#]db[gb]}/g1f#1}[=a]2/g1a1@90[/b]3[ec#\a]8(=a1\a1=e1|1[/a]3)2[/g]2=a1e1@180[/a]2[ec#\f#]6=f#[}/b]\f#=c#[{f#a/d\b]8=b\b=f#b[=f#]2/e1f#1[%7\g=dgb]6%7/g[f#]2=d[d]/g[a][=f#\ad]6/a=d[a]2/f#[d]2=a[c#e/c#]8[\A]\r"
"/use /F#eEp6/d1e1[\f=cfa]6/f[e]2=c[c]/f[g][=e\gc]6/g=c[g]2/e[c]2=g[db\b]8[g]/EdDp6/c1d1[\e.b.=e.g]6/e.[d]2\b.[b.]/e.[f][=d\fb.]6/f=e.[f]2/d[=b.]2f[ca\a]8[f]/DcC=B.[/C]p\e1e.1@90[\d][%7=da/d]8%8(/d1(=d1a1/d1[\d]1)2=d1@180([\d]8=|1/c#=da/c#|2da/c#=d|3bdgb|4dgbd)4|1[\d]8=adgadg[%9\c#/c#=c#]ad@90[\d=d/d]8[%6]{)2[\d]8=(a{de)2[%7/d]2=a[/e]=d)3@85[\g=b/d]G@80[\a/c#]F#@75[\b=f#a/]D@70[=c#ea/]D@90[\d=d/d]9%6|5adgadg[{{/c#=c#]ad@90[d/d]9{|6@-40(ade@-40)2[%4/c#=c#a]6\a{C#[d=d/d]9}D9)6\r"
"/narrate \"Spring\" by Coriakin\r"
"/useitem left /add vibra\r"
}
"\springbycori"
{
call spring
}

**Comment by mehancl** [comment]
"Cozy with You" played about 5-6 seconds late for Clieunk users causing issues with lyrics syncing.

cozywithyou
{
"/narrate \"Cozy By The Fire With You\"\r"
"/equip instrumentcase\r"
"/useitem left /remove gitor\r"
pause 1
"/equip gitor\r"
pause 1
"/use /part p4@100=%8cd[%1](([c]8E8@175G6/c1@100[\b]9/DC6=b[\a]9/C8=ag[\g]7=E7p1de[\f]9=FGA[\e]6=Ec\ga=c|1[\f]8=FE@175F5e1f1@100[\g]7=G7p1cd[%7])2|1@175[\d]7=F5g1f1@100[%8E\]%7ef@175[=D]7\g1f1g5@100[\c]8%8([=C]8p\efg!bg|4[%5e]2=c[\f]2=d)4([%6c]8[%8=e]6p[%7\g]8p[=c]6p[d]4p[%8e]p%9g[g]9[%/d][%8\b]6p[=d]p[%9/c]p[%7\b=d]p[%8b]p[%6d\b]2p[%8/c]8[%7=cg\a]8p%7b=ce%8[%6c]2a[\b]2=g[%7ce\g]8p%6b=ce[%6\b]2%8=d[e]2c[\fg=c]8[%8f]8%6\a[a]p[%8=g]p[%6\ag]p[%8=a]p\f@150[%5\e=c]6[%7E]6p3[%5\g]3p1%7=e\r"
"/use /part 1d1@100[%7c]2%5\e[g]2e[a]2f[=c]2\e|1[%8=f]\a=c[e]\g=c@175[f]6\Ap1[%7\b]8p1[=d]7p1%9G7%6\Gp3%7@100=cd|2@150[%6\a=]6%8Fg1f1[\G]6=E6@175[%9D]7%7\B5[=a]1\a1[=}b]1\g1@100[%8\ac=C]8[%/c]8%8\fga=c[e]2[%6/e]2=c[/g][%=g]2\b[B][%6/b][%8\fa=g]8pd[%6/b#][%C=g]p=e[A][%6/a]=c\f[/g]8[%8\Eb]8[%=G]8\pg=dc[e][%6/e]\bg[/c]8[%=C]8[%7\fga]8\pagfef1e1[%6\dfa]8[%8=d]8%7pc\ag[=d]2\f[=e]2\g[%9=f][%7d]\ag[=c][%9a]\fe[=g][%7\g]df[%8=e]8[%6d\a]8%6\eab=ed\b1a1[d\g#]8[%9=e]%7\ea[=g#]\b=e[a]2c[b]2[%7\r"
"/use /part \g#=]2d[%/c]8[%8\a]8%8fga[%/c]=c[%8ac]2[%/c]2\a[/d]2[%8=bd]2\g[/e=e]6[%6g\fa]8pga[%9/ec]2%7=c[b/d]2\b[/c=a]2\f[%6\Eb]8[%8=Gb]%6\G[b=g]\E@175[%7g=db]7%9/d5e1d1@100[%c]8[=cea\f]8p4[f]p4@175/%8c5f1g1@100[%8a]8[%6=f\da]8defa[%8/g]2\b[/f]2\a[%9/e][%7=cg\ga]8pa[%9/d]\bg[/c]\af[%/d]8[%8=db\g]8%9G3(d1g1a1b1{+)2d1[%7G=db]\Gp4=%5cd[%5c]8%6E8@175G6/c1@100[\b]9/DC6=b[\a]8/C8=G[\g]7[{=c]7E7p1(de[c]9[}\f]9=FGA[\e]6[{=c]6|1E6\ga=c[%5c]8[%6\f]8=%7FE@175A5g1f1@100[\b][%7g]7=%8G7p1cd[%6c\r"
"/use /part ]8%7eE6@175G5%8/c1d1@100[%7\b]9%9/E6{dc=b@67[\%6a]8%8/C8@100[%5\g=e]7[%4c]7p8%7[%5])2Ec\ga=c@175[%6\d]7%8=F5g1f1@100[%9E\g]%7ef@175[=D]7\g1f1g5@100[%\c]8([%7=C]8p\efg!bg|4[%6e]2%8=c[\f]2=d)4)3[%8\F=f][%6CD]%6\a[a]p[%8=E]p\g[=a]\a1g1f[%7\DGB=D]8[%9G]7p4%7\g3p1=cd[%6c][%8e]2[\c]8p[%6g]6[=e]6p[%7c]p%7d@175[c\g]7%8=e5g#1%9b1@100[g#b]8[%/e\e]6p[%8g#]p[b]p[=d]2%/f[\g#][%/e]p[%8\b]2p[%9/d][%7=ca\f]8p%6b[%8/c=a]6cec[a]2\f@175[%8/c]7[%6=ca\f#]7p1(a1+c1}f#1)2@150[%8\f#/c]6%b#6@10\r"
"/use 0p8=%6A[%7g]8[%5\g=ce]8pc\gf[%8=e]\e[=c]\f[%7eg#b]8[%9=e]2p[d]6%7\g#ab{=e}\b[%=c]8[%8\e]8%8age%7c[%9a]2c[=c]2\e[%8=d]8[%6\f#a]8%6D[d]8p4=A[%7g]8[%5c\fa]8p%5ga=c[%7e]2\g([=c]2\a[%6dgb]8|1[%8=e]2p[d]6%7\gab=[a]\ag[%7egb]8[%9=g]p\g[=e]6\abg[=c]2\a[%8=d]8[%6c\fa]8p4%5F%7=A[%5\fa=c]8[%7g]p%5\g[=e]6\a=c\g)2[%8=e]2p[d]6p%7\g%8ga=c@175[%6\da=c]7%8F5g1f1[\eg=c]7E7}[\fgb]7=d1c1}D5@100[%7\c]8([=C]8p%6\efgbg)3@100[%5\cg=]8%6C8cd)2@170[\d]8=Fgf@80[%8E\]%7E@140[=D\d]8G8@60[cg]9=c9\r"
}

**Comment by mehancl** [comment]
Dandelion: A31 Cannot hear 1 of Xepel’s songs. Others can hear it. I could hear his other songs before this one. • You hear Xepel’s music...
Xepel starts playing his violène.

Failed to play song.: unexpected(got: “1”)
(Xepel): Lost Hope

https://clieunk.slack.com/archives/C018PCWS9T2/p1604201082123500

(Violene)
"/use /part @180%4(\a8@-10}g8@-10}f8@-10}e6g)2%(@[\a]8=ab/cd[\g]8/e=gab[\f]8/d=fga[\e]8/C=B|1[\a]8/c=ab/c[\g]8/d=g/cd[\f]8/c=bag@60[\e]8=A=G|3[\a]8/c=ab/c[\g]8/d=g/cd[\f]8/c=bab@60[\e]8/C=B|2[\a]8/c=ea/c[\g]8=bdgb[\f]8=acfa@60[\e]8=g\b=e3g1|4[\a]8/c=ba/c[\g]8=bag/d[\f]8=agfa@60[\e]8=gae3g1)4\r"
pause 1
"/use /part @\AG@-10FE@-10\a=e\gb@-10\f=d\eb@-10[\a=e]p4[\gb]p4@-10[\f=d]p4[\eb]\e1g1b1=e1@60([\a]8=a1g#1a1/c1e1c1=e[\g]8=e1d#1e1g1B[\f]8=f1e1d1c1d1f1a[\e]8=b1g1b1e1|1+E!e1g1b1/e1)2@(%[%\a]8/a{ec{=a[%6\e]8=e{c\a{e%[%\g]8/g{e=b{g[%6\e]8=e{\bg{e%[%\f]8/f{d=a{f[%6\d]8=d{\af{d%[%\e]8/e={bg{e[%6\b]8b{g}E)2@60(%[%\a]8=aa1b1/c1e1=a1g#1@+7[\g]8=g1e1g1b1/e=e@+8[\f]8=f1e1f1d1f1a1g1f1@+7[\e]8=e1\b1=eb3g1@+8)2[\a]8a1=c1e1a1/c1e1a[\g]8/g1e1=b1g1e1\b1g[\f]8f11a1=d1f1a1/d1f[\e]8/e1=b1g1e1\b1g1e6\r"
pause 1
"/use (@{[{\a]8=ab/cd[\g]8/e=gab[\f]8/d=fga[\e]8/C=B|1%8[%8\a]8/c=ab/c[\g]8/d=g/cd[\f]8/c=bag@60[\e]8=A=G|3%4[%4\a]8/c=ab/c[\g]8/d=g/cd[\f]8/c=bab@60[\e]8/C=B|2%6[%6\a]8/c=ea/c[\g]8=bdgb[\f]8=acfa@60[\e]8=g\b=e3g1|4%2[%2\a]8/c=ba/c[\g]8=bag/d[\f]8=agfa@60[\e]8=gae3g1)4{[{\a]8=ab/cd[\g]8/e=gab[\f]8/d=fga[\e]8/C=Ba8\r"
"/narr Lost Hope by Xepel\r"

**Comment by skirwan** [comment]
My current thinking is that there are two problems -- (a), the music parsing logic is much slower than it ought to be, and (b) I still have a problem with my UDP retry logic and I'm still occasionally dropping packets under some circumstances.

I think I've figured out some of the major slowdowns causing (a) and they'll be fixed in the next release -- parsing is now essentially instant from a human POV.

**Comment by skirwan** [comment]
Or maybe there isn't a packet loss issue here -- The issue with 'Lost Hope' was just that my parser doesn't expect multi-digit durations (it has an `f11` that wasn't parsing right).

**Comment by skirwan** [comment]
Closing this because I think I'm at a point where discrete issues will be more helpful.
