### ISSUE TITLE
Click toggles cursor gets interrupted by notifications 

### ISSUE THREAD

**Issue by mcmanuss8** [skirwan/clan-lord-client-issues#165]
Fairly easy to reproduce for me now:

* Enable click toggles
* Click somewhere, start moving (cursor changes to + ... this is good)
* Force another application to send a notification. For me, this is easy to do by having iTunes notifications turned on and change the currently playing track using a keyboard shortcut or waiting til the song is over.
* Notice cursor changes back to pointer (this is bad)

This frequently causes falls for me. :(

**Comment by skirwan** [comment]
Resetting the cursor in a loop now on pre-Big Sur systems.  Currently doing so at 15fps; will monitor to see if that needs to be upped.

**Comment by skirwan** [comment]
Next build should fix this and #141 by hitting the problem with a big ol' rock...
