### ISSUE TITLE
infoing an exile doesn't update their class icon in the players window

### ISSUE THREAD

**Issue by mcmanuss8** [skirwan/clan-lord-client-issues#169]
This is pretty minor. To reproduce is a little difficult but not hard with a new exile.

1) Login as one character
2) Create a new character in another client, they startoff with no class (exile)
3) Clieunk will assign them no icon (good)
4) Get the new character to become a healer or fighter or some such 
5) /infoing the exile will reflect the new class, but the player window won't update

**Comment by mcmanuss8** [comment]
Looks like a log out/log back in of the new exile doesn't fix it, but logging out of you, the observing player does fix it.

**Comment by skirwan** [comment]
This should be fixed with the A64 charDB.
