### ISSUE TITLE
double clicking in player window crashes Clieunk

### ISSUE THREAD

**Issue by Kazei** [skirwan/clan-lord-client-issues#171]
This is consistent and repeatable and has been happening over the last few versions for me. I do run with a larger than minimum (not that much larger) game window, I don't know if that makes any difference. Happened again today, on version 52, 2017 iMac, latest Big Sur. I think this is the right crash log:

[ClanLord_2021-05-04-140503_iMacs-iMac.crash.zip](https://github.com/skirwan/clan-lord-client-issues/files/6423242/ClanLord_2021-05-04-140503_iMacs-iMac.crash.zip)

**Comment by dfsw** [comment]
This appears to be working as intended in latest, double clicking on a player provides /info for player as expected,
