### ISSUE TITLE
Text Style Updates

### ISSUE THREAD

**Issue by mehancl** [skirwan/clan-lord-client-issues#187]
- Self over /think and /thinkto should be same color as self standard speech
- /labeled friend in /think should be green but **not** italic or underlined
- /labeled friend in /thinkto should be green, underlined, **and** italic 
- non-/labeled should be standard text (black), not underlined, not italic.

**Comment by skirwan** [comment]
I believe this is now implemented for the next release.  But I'm leaving this issue open because... I dunno, this doesn't seem right.
