### ISSUE TITLE
Bard - DT Client/Tunehelper ignore numbers attached to no note; Clieunk does not

### ISSUE THREAD

**Issue by mehancl** [skirwan/clan-lord-client-issues#190]
Ran into an issue with a duet that was desynchronized post-A68. Analyzed it and realized in DT Client/TuneHelper an errant number, like 4, not attached to a note is ignored by DT/TuneHelper. In Clieunk it's a "silent" note that will throw off a duet for example because it adds in extra beats to a song. 

Notes: [\a]6e4\b4=c4[d]6\a4=c4\b4[a=e]6a6a6[=f/f=a]6f6f6[e\b]6=e4c4g#4**4**[\a=a]6a6a6[b\b=f]6b6b6[\a=e]6=a4/e4c4[=d/d]6d4c4d4[=d/d]6=d6d6

You can see the extra 4 bolded. This 4 has been in this song since I wrote it but breaks it in Clieunk. It obviously shouldn't work in DT client but it does, so I'm concerned others might have rogue numbers without knowing. In a perfect world, Clieunk would play it like DT, but also acceptable is an error.

**Comment by skirwan** [comment]
Actually Clieunk is reading that as 44 and playing that single note for 11x as long, I think.

So the behavior in DT is to use the first digit and ignore subsequent?

**Comment by mehancl** [comment]
AH 44 that makes more sense, I couldn't understand why it was so long. Yes, in DT and TuneHelper (tested in both) it just ignores the errant 4.

**Comment by skirwan** [comment]
Fixed for next release.
