### ISSUE TITLE
Login form does not properly unlock submit button

### ISSUE THREAD

**Issue by spkzest** [skirwan/clan-lord-client-issues#203]
Seems like this has to be a code bug, but so far only reported on Monterey.

https://clieunk.slack.com/archives/C018PCWS9T2/p1636209598084200

**Comment by skirwan** [comment]
Near as I can tell, Monterey got picky about the fact that I had a `NSSecureTextFieldCell` inside of something that wasn't descended from `NSSecureTextField`, which essentially broke the password field.  This manifested as Cocoa Bindings being 'broken', so I rewrote without bindings... but it still didn't work so I had to split `SavedAccountTextField` in half to make `SavedAccountSecureTextField` that inherited from the correct place.

Keeping #209 open to track the cleanup.

https://github.com/skirwan/clan-lord-client/commit/ece33f81fcccf7df0671bf18ba54e10c276b8203

**Comment by atomical** [comment]
Is the client not open source?
