### ISSUE TITLE
Text Log for 2nd window IDed as Inventory

### ISSUE THREAD

**Issue by noivad** [skirwan/clan-lord-client-issues#232]
When you launch multiple windows the text log of the second window is named Inventory, so you can’t pull the real inventory window forward with the window menu (under open windows, not the command-G inventory) . Inventory window doesn’t switch to second screen either. (Mac OS 10.15 Catalina)

**Comment by skirwan** [comment]
Fixed in https://github.com/skirwan/clan-lord-client/commit/b75cadb57e588f2f335e8f1ffe3df9f39d118512
