### ISSUE TITLE
Shares not shown after relaunch

### ISSUE THREAD

**Issue by noivad** [skirwan/clan-lord-client-issues#233]
If you have to quit the client while logged in, when you relaunch and reconnect, it doesn’t show your shares in or out in the players window.

**Comment by skirwan** [comment]
I'm not able to reproduce this.  It can take some time for share information to be delivered to the client, especially if there's a lot going on or there's a long players list.

Can you reliably reproduce this?

**Comment by noivad** [comment]
I can no longer reliably reproduce this. On B.8 it was happened less if at all. Maybe whatever mechanism caused it was written out of the code?

**Comment by skirwan** [comment]
Dunno.  Gonna close this and open a new one if it comes back.
