### ISSUE TITLE
Emoji in text box causes deadens input

### ISSUE THREAD

**Issue by noivad** [skirwan/clan-lord-client-issues#240]
As title says: I accidentally entered an emoji into the text box as the first character, and it disabled being able to type & move. I had to quit the app and relaunch. The relaunch hung on checking updates. I closed and opened again: the same “checking for updates” spun. Quit & finally opened app with option click, and it worked.

**Comment by noivad** [comment]
As title says: I accidentally entered an emoji into the text box as the first character, and it disabled being able to type & move. I had to quit the app and relaunch. The relaunch hung on checking updates. I closed and opened again: the same “checking for updates” spun. Quit & finally opened app with option click, and it worked.

**Comment by skirwan** [comment]
Fixed with https://github.com/skirwan/clan-lord-client/commit/cfb682d6f1d0e253f666ce443d30c3376306d89f and https://github.com/skirwan/clan-lord-client/commit/b212f9bdb3d3d964aa4620773eaf960088748d6a
