### ISSUE TITLE
Looks like "#" syntax for comments in macro files are suppo…

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#31]
MrFancyPants: Looks like "#" syntax for comments in macro files are supported in DT's client, but not here. Removed those lines and that helped<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1597798902005600<br /><br />Skirwan<br /><br />I need to look at this more -- in the body of a macro, `#foo` seems to be treated as `"#foo"`, which makes me wonder what's actually happening is that 'emit' lines in the global scope are silently ignored.

**Comment by mcmanuss8** [comment]
Lines starting with # seem to be ignored now - think this can be closed.

**Comment by mcmanuss8** [comment]
Actually, not fully fixed. One liners are ignored (good), still throws a warning on this case:

```
#f13 
#{
#	"/pref maxnightpercent " night "\r"
#	if night == 0
#	setglobal night 100
#	else
#	setglobal night 0
#	end if
#}
```

**Comment by skirwan** [comment]
I think the warnings are appropriate -- DT is ignoring those lines because it can't figure out how to parse them, not because it thinks they're commented out.  For instance:

```
"/test"
{
	# "Hello world!\r"
}
```

That actually causes you to say "#Hello world!" -- `#` is interpreted as a variable name, and that variable doesn't exist and gets echoed.

Your example is safe-ish because you're commenting out the whole macro, but in other cases it's going to cause unexpected behavior.
