### ISSUE TITLE
I have a /whoclan macro (that I never use anymore so I just…

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#32]
MrFancyPants: I have a /whoclan macro (that I never use anymore so I just stripped it) that was causing macro parsing to barf. It seemed like a line break issue, so I tried converting from dos to unix line breaks on the file but no change. I'll put the original file up here in case it's useful<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1597798956007700

**Comment by mcmanuss8** [comment]
This macro works now, even though it's terribly written
