### ISSUE TITLE
Clieunk UI not reflecting disconnection

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#34]
MrFancyPants: some weirdness. I signed off in the library. No obvious way to join back in as another character - screen didn't go fully grey like it does when I disconnected previously (toggling between clients)<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1597801408013100

**Comment by spkzest** [comment]
The TCP changes in A71 seem to have finally nailed this.
