### ISSUE TITLE
Here's another old macro that I don't ever use so it can di…

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#38]
MrFancyPants: Here's another old macro that I don't ever use so it can die in a fire, but Clieunk barfs on it<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1597806326018000<br /><br />"/oe"<br />{		
	if @my.forehead_item == "orga eye"
		goto End
	else
		"/equip Orga Eye\r"
		pause 10
		goto iloop
	end if
	
	label iloop
		if @my.forehead_item == "orga eye"
		{	
			message "»»»»»» ORGA EYE EQUIPPED ««««««"
			pause 30
			goto iloop
		else
			goto Endl	
		end if
		}
	label End	
	"/equip sun\r"
	label Endl
}<br /><br />* An error occurred: syntaxError(message: "Unexpected token \'openCurly\'.", lineNumber: 146,<br /><br />It's barfing on the { after == "orga eye"<br /><br />Shakyamuni<br /><br />Mine is part of my idle macro... which still is dead. <br /><br />Skirwan<br /><br />This may work in A15 -- I _think_ I'm now doing the same weird quasi-permissiveness with curly braces as the DT engine.

**Comment by mcmanuss8** [comment]
This works now, can close
