### ISSUE TITLE
I can't really verify this one on a DT mac client currently…

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#39]
MrFancyPants: I can't really verify this one on a DT mac client currently, but command-numpad-* and control-numpad-*  don't work, although numpad-* do work (see my "Default" file for examples up in the /whoclan bug report)<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1597854778028700<br /><br />Shakyamuni<br /><br />Yeah I am having difficulty with the modifiers.. But oddly my cmd-f15 to purge macro works fine<br /><br />Skirwan<br /><br />The handling for the `numpad` modifier got semi-rewritten a few versions back -- is thus working by any chance?<br /><br />MrFancyPants<br /><br />yes, this works now

**Comment by mcmanuss8** [comment]
This works now, can be closed
