### ISSUE TITLE
* An error occurred: variableNotFound(name: "@text")

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#65]
MrFancyPants: * An error occurred: variableNotFound(name: "@text")<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1598478329108600<br /><br />I have these macros because sometimes I'll type something out then decide I might want to yell or whisper it:<br />command-w
{
	set @env.echo true
	"/whisper " @text "\r"
	set @env.echo false
}
"/y"    "/yell "    @text "\r"
command-y
{
	set @env.echo true
	"/yell "    @text "\r"
	set @env.echo false
}<br /><br />Skirwan<br /><br /><https://clieunk.slack.com/archives/C018PCWS9T2/p1596094879003900|Y>eah, that’s a known one that I haven’t gotten to yet — <https://clieunk.slack.com/archives/C018PCWS9T2/p1596094879003900><br /><br />I don't remember when I added support for `@text` in keystroke macros (may have been drinking), but it looks like I did at some point.  Any chance these work now?<br /><br />MrFancyPants<br /><br />yes, this works now

**Comment by mcmanuss8** [comment]
works now, can be closed
