### ISSUE TITLE
Saw "/m_interrupt" (on a line all by itself) show up in sid…

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#72]
MrFancyPants: Saw "/m_interrupt" (on a line all by itself) show up in sidebar and text log just now - haven't seen that before<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1599243517015100<br /><br />Skirwan<br /><br />Yeah, that’s the command the server sends to force-kill running macros.  There’s code to handle it but I think I accidentally broke it while refactoring at some point.  Thanks for reminding me.<br /><br />Should be fixed in A23.

**Comment by mcmanuss8** [comment]
This is fixed
