### ISSUE TITLE
move commands don't work exactly as in DT clients

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#77]
MrFancyPants: move commands don't work exactly as in DT clients<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1600018857035200<br /><br />Here's mine - numpad without control does posting. With control does running. The posing works fine, the running does not<br /><br />They're implemented in A23 in theory but don't work for me :disappointed:<br /><br />I don't have /move instead just have "move" - which works in DT client, but not this<br /><br />Soul Hunter<br /><br />Ah I withdraw my duplicate note

**Comment by mcmanuss8** [comment]
works now, can be closed
