### ISSUE TITLE
Crash after changing audio output device

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#84]
Ryder: There seems to be a bug regarding sound for me with alpha 29.  If i start the app using a given audio output and then the system switches to another, the app no longer produces sound and crashes when i open the system sound prefs to change output targets.  Hardware: 2019 MacBook Pro, 10.15.7.<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1601229863019300

**Comment by skirwan** [comment]
I think this was caused by not re-opening the `AVAudioEngine`, and if that's correct it should be fixed.

**Comment by ryanima1** [comment]
Sorry, had not tested this in a while.  Swapped between 4 different sound targets and made some noise in game.  ALl worked as expected.  Verified fixed as far as i can tell in A38 on OS 11.0.1 release.  

Thank You!
