### ISSUE TITLE
Occasional very long delays before bard music starts playing

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#85]
Ryder: Bard concert bug.   Music is awesome on this client, but one song in particular somehow had a huge delay in starting.  so much so that it ended about 20 seconds after everyone was done clapping.<br />--
• You hear Coriakin's music...
Coriakin starts playing his vibra.
(Coriakin): "Spring" by Coriakin
Creed ponders, "nice!"
Arkin is no longer Clanning.
Inu's Packmule ponders, "so happy!"
Snacks ponders, "Good choice"
(Melatopia strains her neck trying to watch)
(Aurelie smiles.)
You concentrate on sending your message to Snacks.
You think to Snacks, "is music playing?"
You are still concentrating on your last thought.
Snacks thinks to you, "for me it is"
You concentrate on sending your message to Snacks.
You think to Snacks, "oh, now it started"
--<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1601237626024300<br /><br />Skirwan<br /><br />Interesting.  Did anyone else <!here> get a delay on that song?<br /><br />Ryder<br /><br />also of note that all songs prior to and after that thus far seem to line up with the title message and when people clap etc.<br /><br />Mehan<br /><br />Sorry I wasn’t at the concert :disappointed:<br /><br />I can get the notes from Cori and we can test though at some point.

**Comment by skirwan** [comment]
A thought occurs at 3AM: Do I just have this in a dispatch queue with the wrong QoS?

**Comment by skirwan** [comment]
Doesn't look like it.

**Comment by mehancl** [comment]
Adding to master ticket #163
