### ISSUE TITLE
Command shortcuts don't work as expected. For example in DT…

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#90]
MrFancyPants: Command shortcuts don't work as expected. For example in DT client /g will autocomplete to /give without me having to hit tab or anything. In Clieunk it silently does nothing :disappointed:<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1601694219043300<br /><br />Example: /g MrFancyPants 1000<br /><br />Skirwan<br /><br />That just worked for me<br /><br />`/g Skirwan 1` flipped a coin as expected<br /><br />MrFancyPants<br /><br />Weird<br /><br />Maybe something in my macro file (or not in my macro file)<br /><br />Skirwan<br /><br />There's no client-side logic for the server side commands, so I'm not sure how this would fail unless somehow it was just failing to send the command.  Which would be a really bad bug obviously.

**Comment by mcmanuss8** [comment]
This was because I had this old macro I forgot about:

"/g"	"/give " @text

Which now works since we have @text support

Can close
