### ISSUE TITLE
Bug A30: If the player list is scrolled all the way to the …

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#91]
Soul Hunter: Bug A30: If the player list is scrolled all the way to the bottom it will randomly jump around in its position and scroll itself back up to about middle randomly<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1601861728045900<br /><br />Mehan<br /><br />That’s a ghost<br /><br />Soul Hunter<br /><br />I guarantee my computer isnt haunted I pay a lot of money for someone to check each week for me.<br /><br />Jamboree<br /><br />It was jumping around for me too, but only when I first signed on and then it was fine.

**Comment by skirwan** [comment]
The code to update the players list does a full refresh of the table view for any change, instead of doing a row-wise update. Very easy to reproduce with a ranger toggling a morph on and off. Thanks Aymi!

**Comment by dfsw** [comment]
still present

**Comment by skirwan** [comment]
Should be fixed with A64 changes.
