### ISSUE TITLE
Player list does not mark people as sharing, game window is correct

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#94]
Soul Hunter: Bug A30 - It is possible to get into a state where the player list does not mark people as sharing you but the game window reflect its properly, see Elenis in attachment<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1602875257055900

**Comment by dfsw** [comment]
havent seen this in a long time, perhaps fixed
