### ISSUE TITLE
Bard music doesn't get canceled on logout.

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#96]
Skirwan: Bard music doesn't get canceled on logout.<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1602907414057400<br /><br />Mehan<br /><br />Just saw this. Happens in DT client too. Music doesn’t stop until you quit the client, so I’d say not a bug!<br /><br />Skirwan<br /><br />I’m calling it a bug, it bugs me. <br /><br />Mehan<br /><br />I support you in whatever path you take! :scream:

**Comment by mehancl** [comment]
I'll throw onto this that I kinda like being able to hear a song finish if I log out and don't quit the client. If nobody hates it, and I kinda like it, does that break even to not fixing it?
