### ISSUE TITLE
Bard music containing underscores fails to parse and play

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#99]
Skirwan: &gt; Cloud starts playing his starbuck harp.<br />&gt; * Failed to play song.: unexpected(got: "_")
<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1603678751059400<br /><br />Missed server frame.  Got 6833734 but wanted 6833733<br />Ignoring reliable stream for 6833734, reliable segment isn't in sequence
Got catchup packet 6833735, replayed from 6833733
Frame 6833735, got 3 reliable frames.
BardPlayer command: SongCommand(who: Optional("11729872"), with: [], instrument: 2, forSelf: false, initialVolume: 100, initialTempo: 60, body: ClanLord.SongCommand.Body.partial(notes: "(\\g_\\a#_=d_d#_gp4)2\\a_=c_e_f#_gp4\\g_a#_=d_d#_gp4\\g_a#_=d_d#_g_d#_d_\\a#_g_\\a#_=d_d#_g_d#_d_(\\a#_[g/a]p2\\a#_[=d/g]p2=d#_[g/a]p2=d#_[d/g]p2)3\\a#_[g/a=a]p2=a#_/d_d#_g_d#_d_=a#_[g\\g]p2a#_=d_d#_g_d#_d_\\a#[\\g=g]p2a#_/d_d#_g_d#_d_=a#_[g\\a]p2=c_e_f#_g_f#_e_c_[\\a=a]p2/c_e_f#_g_f#_/e_c_[=a\\a]p2=c_e_f#_g_f#_e_c_[/cef#]9\\a_=c_e_f#_g_f#_e_c_[/df#a]9\\a_=c_=e_f#_g_f#_e_c_[/a#ge]9\\a_=c_e_f#_g_f#_e_c_\\g_a#_=d_d#_g_d#_d_(\\a#_[g/a]p2\\a#_[=d/g]p2=d#_[g/a]p2=d#_[d/g]p2)2\\a#"))
Music from 11729872, group ["11729872"]: PARTIAL
Extending stream existing stream
BardPlayer command: SongCommand(who: Optional("11729872"), with: [], instrument: 2, forSelf: false, initialVolume: 100, initialTempo: 60, body: ClanLord.SongCommand.Body.notes(notes: "[\\g/a=a]p2c_e_f#_g_f#_e_c_[=a\\a]p2/c_e_f#_/g_f#_e_c_[\\a=a]p2c_ef#_=g_f#_e_c_[\\a=a]p2/c_e_f#_g_f#_e_c_[=a\\g]p2a#_=d_d#_g_d#_d_\\a#_[\\g=g]p2=a#_/d_d#_g_d#_d_=a#_[g\\g]p2a#_=d_d#_g_d#_d_\\a#_[=ga#/d]8\\g2_\\a#2_[=a/df#]9=d2_d#2_[/dga#]9=g9"))
Music from 11729872, group ["11729872"]: END NOTES
Updating existing stream<br /><br />Coriakin<br /><br />Looks like Cloud is living in the past! _ hasn't done anything for a long time. Originally it was supposed to make the notes sound more connected ("legato" playing), possibly by extending them slightly, but as far as I know it hasn't done anything for a long time. I suspect most bard music programs just ignore _ characters, and Clieunk can do the same<br /><br />Skirwan<br /><br />:thumbsup:

**Comment by mehancl** [comment]
Ported to master bard ticket #163
